from aiogram.fsm.state import State, StatesGroup

class RegisterStates(StatesGroup):
    waiting_for_api_key = State()
    waiting_for_api_secret = State()
    waiting_for_passphrase = State()


class SettingStates(StatesGroup):
    waiting_for_investment = State()
    waiting_for_leverage = State()
    waiting_for_entry_multiplier = State()
    waiting_for_rsi_length = State()
    waiting_for_rsi_oversold = State()
    waiting_for_rsi_overbought = State()
    waiting_for_tp_ratios = State()
    waiting_for_tp1_value = State()
    waiting_for_tp2_value = State()
    waiting_for_tp3_value = State()
    waiting_for_sl_value = State()
    waiting_for_pyramiding_value = State()
    waiting_for_pyramiding_entry_type = State()
    waiting_for_pyramiding_limit = State()
    waiting_for_trend_timeframe = State()
    waiting_for_sl_on_last = State()
    waiting_for_trailing_stop_type = State()
    waiting_for_cooldown_time = State()
    waiting_for_use_check_DCA_with_price = State()
    waiting_for_trailing_stop_offset_value = State()
    waiting_for_symbol = State()
    waiting_for_symbol_investment = State()
    waiting_for_btc_investment = State()
    waiting_for_eth_investment = State()
    waiting_for_sol_investment = State()
    waiting_for_entry_amount_option = State()